name: Run tests

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt
          pip install flake8

      - name: Run tests
        run: |
          python -m unittest discover -p "test_stack.py" # Run unitests from the default test directory
