name: Run tests

on:
  push:
    branches:
      - 'main'

  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 coverage
          #pip install -r requirements.txt
          pip install flake8
      - name: List directory contents
        run: |
          ls -R
      #- name: Run test    
      #  run: |
      #   python -m unittest "tests/test_stack.py"
         
      # - name: Test with unittest and calculate coverage
      #   run: |
      #     cd src  # Change to src/ directory if your code is inside src/
      #     coverage run -m unittest discover ../tests  # Update path to tests/ if different
      #     coverage xml -o ../coverage.xml
      # - name: Display current directory and list files
      #   run: |
      #     pwd
      #     ls -la
      # - name: Create Coverage 
      #   if: ${{ github.event_name == 'pull_request' }}
      #   uses: orgoro/coverage@v3.1
      #   with:
      #       coverageFile: coverage.xml
      #       token: ${{ secrets.GITHUB_TOKEN }}
